# Generated by Django 4.1 on 2022-09-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peopletag',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'People'},
        ),
        migrations.AddField(
            model_name='generictag',
            name='tag',
            field=models.CharField(default=None, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peopletag',
            name='people',
            field=models.CharField(default=None, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
