# Generated by Django 4.1 on 2022-09-04 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0002_alter_peopletag_options_generictag_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generictag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='peopletag',
            name='people',
        ),
    ]
