# Generated by Django 4.1 on 2022-09-05 05:29

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0003_remove_generictag_tag_remove_peopletag_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='people',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='photoapp.TaggedPeople', to='photoapp.PeopleTag', verbose_name='People'),
        ),
        migrations.RemoveField(
            model_name='photo',
            name='year',
        ),
        migrations.AddField(
            model_name='photo',
            name='year',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='photoapp.year'),
            preserve_default=False,
        ),
    ]
