# Generated by Django 4.1 on 2022-09-14 21:03

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0004_alter_photo_people_remove_photo_year_photo_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['-year']},
        ),
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=-1, scale=None, size=[360, 360], upload_to='thumbnails/'),
        ),
    ]
