# Generated by Django 4.1 on 2022-09-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='thumbnails/'),
        ),
    ]
